# hi! This configures the python global settings for the project.

[project]
name = "LongHaulC2"
version = "1.0.0"
# Needed by both
dependencies = [
    "structlog",
    "msgpack",
    "brotli",
    "requests",
    "dotenv",
    "pip-audit"
]

[tool.setuptools]
# This explicitly tells pip which directories are packages, otherwise it freaks out
packages = ["server", "client"]

[project.optional-dependencies]
# server reqs
server = [
    "flask-restx",
    "sqlalchemy",
    "redis",
    "pymysql",
    "cryptography",
    "flask-compress",
    "flask-limiter",
    "edwh-uuid7",
    "pyMalleableProfileParser",
    "uvicorn",
    "concurrent-log-handler",
    "neomodel",
    "pandas",
    "fastapi",
    "waitress",
    "orjson",
    "docker",
]
# GUI reqs
web = [
    "nicegui",
    "pywebview",
    "httpx",
]
# Development reqs
dev = [
    "pre-commit",
    "ruff",
    "schemathesis",
    "pytest",
]


[tool.ruff]
target-version = "py312"
line-length = 120

exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "logs",
    "*.h",    # exclude implant source
    "*.hpp",  # exclude implant source
    "*.c",    # exclude implant source
    "*.cpp",  # exclude implant source
    "*.md",    # exclude docs
    "*test*",  # exclude any tests
    "*user/*", # exlcude anything in client user folder, which is for python scripts & malleablec2 files

]

[tool.ruff.lint]
# G = Logging, E/F = Syntax/Logic, I = Import Sorting, UP moves old py semantics to new ones
#T201: print statements
# Eventually, do ERA, which finds dead code in comments
select = ["G", "E", "F", "I", "UP", "PERF", "FURB", "T201", "SIM", "ARG","B"]
# Tell Ruff which variable names are actually loggers
logger-objects = [
    "api_logger",
    "server_logger",
    "listener_logger",
    "neo4j_logger",
    "response_pipeline_logger",
    "docker_logger"
]

[tool.ruff.format]
# This ensures Ruff's formatter behaves like Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
