/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // Docusaurus derives IDs by stripping numeric prefixes from filenames
    // (e.g. "1. Commands.md" → ID "02 Implants/Commands").
    // Directories keep their full name in the ID path.
    // The QuickStart ID comes from its frontmatter `id:` field.

    "LongHaul C2 - Quickstart Guide",
    "Project Overview",

    {
      type: "autogenerated",
      dirName: "00 Intro & Setup",
    },
    {
      type: "autogenerated",
      dirName: "01 Listeners",
    },
    {
      type: "category",
      label: "Implants",
      items: [
        "02 Implants/Commands",
        {
          type: "category",
          label: "Modules",
          items: [{ type: "autogenerated", dirName: "02 Implants/Modules" }],
        },
        {
          type: "category",
          label: "Systems",
          items: [{ type: "autogenerated", dirName: "02 Implants/Systems" }],
        },
      ],
    },
    {
      type: "autogenerated",
      dirName: "03 Scripting",
    },
    {
      type: "autogenerated",
      dirName: "04 API Reference",
    },
    {
      type: "autogenerated",
      dirName: "05 Testing",
    },
    {
      type: "autogenerated",
      dirName: "06 Network Profiles",
    },
  ],
};

module.exports = sidebars;
