/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    // Docusaurus derives IDs by stripping numeric prefixes from filenames
    // (e.g. "1. Commands.md" → ID "02 Implants/Commands").
    // Directories keep their full name in the ID path.
    // The QuickStart ID comes from its frontmatter `id:` field.

    "Project Overview",
    "LongHaul C2 - Quickstart Guide",
    {
      type: "category",
      label: "Intro",
      items: [{ type: "autogenerated", dirName: "00 Intro" }],
    },
    {
      type: "category",
      label: "Listeners",
      items: [{ type: "autogenerated", dirName: "01 Listeners" }],
    },
    {
      type: "category",
      label: "Mimicry",
      items: [{ type: "autogenerated", dirName: "06 Network Profiles" }],
    },
    {
      type: "category",
      label: "Implants",
      items: [
        "02 Implants/Commands",
        {
          type: "category",
          label: "Modules",
          items: [{ type: "autogenerated", dirName: "02 Implants/Modules" }],
        },
        {
          type: "category",
          label: "Systems",
          items: [{ type: "autogenerated", dirName: "02 Implants/Systems" }],
        },
      ],
    },
    {
      type: "category",
      label: "Scripting",
      items: [{ type: "autogenerated", dirName: "03 Scripting" }],
    },
    {
      type: "category",
      label: "Dev & Advanced",
      items: [
        {
          type: "category",
          label: "API Reference",
          items: [{ type: "autogenerated", dirName: "04 API Reference" }],
        },
        {
          type: "category",
          label: "Testing",
          items: [{ type: "autogenerated", dirName: "05 Testing" }],
        },
        {
          type: "category",
          label: "Advanced Setup",
          items: [{ type: "autogenerated", dirName: "Advanced Setup" }],
        },
      ],
    },
  ],
};

module.exports = sidebars;
