name: Deployment Test - Ubuntu 22.04, 24.04, Python 3.10, 3.11, 3.12

# for testing deployment

on:
  push:
    branches: [ "main" ] # commented out to test pushes
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        #https://github.com/actions/runner-images - for ref
        os: [ubuntu-22.04, ubuntu-24.04]         # Testing different Linux versions
        python-version: ['3.10', '3.11', '3.12'] # Testing different Python versions

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r ./server/src/server/requirements.txt

    - name: Remove pre-installed Docker
      run: |
        sudo apt-get purge -y docker-ce docker-ce-cli containerd.io
        sudo apt-get autoremove -y
        sudo apt-get autoclean

    - name: Deploy
      run: |
        # Testing out deployment
        sudo -E make deploy
        echo "Successfully deployed LongHaulC2"

    - name: Run tests
      run: |
        # Testing out deployment
        # sudo make deploy
        echo "Successfully running tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}"

    # not yet - need to clean up some API stuff first
    # - name: SchemaThesis
    #   run: |
    #     echo "Starting Schemathesis: ${{ matrix.os }} with Python ${{ matrix.python-version }}"
    #     pytest -s -v tests/server/api_schematesis.py

  # security job for security scans/sanity check
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        # use latest pip, then install our reqs
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[server,web,dev]"

      - name: Dependency audit
        # || true means notify, as it ret's true & GH thinks it succeeded then
        run: |
          python -m pip install pip-audit
          pip-audit || true