name: Code test - Pytest

on:
  push:
    #branches: [ "main" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  pytest:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Deploy
      run: |
        # Testing out deployment
        sudo -E make deploy
        echo "Successfully deployed LongHaulC2"

    - name: Run tests
      run: |
        # Testing out deployment
        sudo make test
        echo "Successfully running tests"