name: Pytest - Ubuntu 22.04, 24.04, Python 3.10, 3.11, 3.12

# for testing pytest

# ** should run on all
# on:
#   push:
#     branches: [] # [ "**" ]
#   pull_request:
#     branches: [] # [ "**" ]

on:
  workflow_dispatch: # Allows manual execution from the GitHub Actions tab

jobs:
  deployment:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        #https://github.com/actions/runner-images - for ref
        os: [ubuntu-22.04, ubuntu-24.04]         # Testing different Linux versions
        python-version: ['3.10', '3.11', '3.12'] # Testing different Python versions

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Remove pre-installed Docker
      run: |
        sudo apt-get purge -y docker-ce docker-ce-cli containerd.io
        sudo apt-get autoremove -y
        sudo apt-get autoclean

    - name: Dev Install
      run: |
        make dev_install CI=1
        echo "Successfully installed dev of LongHaulC2"

    - name: Run tests
      run: |
        # Testing out deployment
        # sudo make deploy
        make local_tests
        echo "Successfully running tests on ${{ matrix.os }} with Python ${{ matrix.python-version }}"
